"""Pydantic schemas for Big Pickle LLM structured responses.

Enforces strict compliance with Sections 18-20 of the Dynamic Infrastructure
Impact Intelligence Platform architecture specification.
"""

from __future__ import annotations

from typing import Any, Literal
from pydantic import BaseModel, Field, field_validator

#: Predicates an LLM may extract. Anything outside this set is rejected.
ALLOWED_EXTRACTED_PREDICATES: frozenset[str] = frozenset(
    {
        "event.gathering",
        "event.movement",
        "event.movement_direction",
        "event.estimated_crowd",
        "event.expansion",
        "event.status",
        "event.route",
        "event.footprint",
        "location.name",
        "infrastructure.disruption",
        "transit.delay",
        "roadway.congestion",
    }
)

#: Categories the LLM must never emit. Checked before any write.
FORBIDDEN_LLM_CLAIMS: frozenset[str] = frozenset(
    {
        "emergency.evacuation",
        "emergency.evacuation_destination",
        "road.authoritative_closure",
        "participant.criminal_intent",
        "group.dangerousness",
    }
)


class ExtractedClaim(BaseModel):
    """An individual factual claim extracted from unstructured text."""
    predicate: str = Field(..., description="Standardized predicate name")
    value: Any = Field(..., description="Extracted value (bool, str, int, float, list)")
    confidence: float = Field(default=0.8, ge=0.0, le=1.0, description="Confidence score")
    evidence_span: str | None = Field(default=None, description="Exact text excerpt supporting claim")

    @field_validator("predicate")
    @classmethod
    def validate_predicate(cls, v: str) -> str:
        clean = v.strip().lower()
        if clean in FORBIDDEN_LLM_CLAIMS:
            raise ValueError(f"Forbidden claim predicate: {clean}")
        return clean


class ClaimExtractionResponse(BaseModel):
    """Structured response for claim extraction."""
    observation_id: str
    claims: list[ExtractedClaim] = Field(default_factory=list)
    rejected_claims: list[dict[str, Any]] = Field(default_factory=list)
    reason: str | None = None


class EventResolutionResponse(BaseModel):
    """Semantic deduplication and event resolution decision."""
    decision: Literal["existing", "new", "uncertain"] = Field(
        ..., description="Whether to merge into an existing event, create new, or mark uncertain"
    )
    event_id: str | None = Field(default=None, description="Target event ID if decision is 'existing'")
    confidence: float = Field(default=0.5, ge=0.0, le=1.0)
    reason: str = Field(..., description="Explanation for the resolution choice")
    matching_signals: list[str] = Field(default_factory=list)


class CapabilityRecommendation(BaseModel):
    """Analytical capability recommended by the LLM orchestrator."""
    capability: str = Field(..., description="Name of registered analytical capability")
    reason: str = Field(..., description="Rationale for triggering capability")
    priority: float = Field(default=0.5, ge=0.0, le=1.0)
    cost_tier: Literal["cheap", "medium", "expensive"] = "medium"


class CapabilitySelectionResponse(BaseModel):
    """Dynamic capability selection recommendation."""
    recommended_capabilities: list[CapabilityRecommendation] = Field(default_factory=list)
    reason: str = Field(default="ok")


class InfrastructureHypothesis(BaseModel):
    """Hypothesis about potential infrastructure relationship deserving examination."""
    infrastructure_type: str = Field(..., description="Type of infrastructure, e.g. roadway, transit, bridge")
    target_id_or_name: str = Field(..., description="Name or identifier of target infrastructure")
    potential_impact: str = Field(..., description="Nature of anticipated disruption")
    urgency: Literal["low", "medium", "high", "critical"] = "medium"
    justification: str = Field(..., description="Evidence or topological justification")


class InfrastructureHypothesisResponse(BaseModel):
    """Set of infrastructure hypotheses generated by LLM."""
    hypotheses: list[InfrastructureHypothesis] = Field(default_factory=list)
    uncertainty: str = Field(default="Unverified hypotheses requiring deterministic model validation.")


class EvidenceSynthesisResponse(BaseModel):
    """Structured synthesis of multiple observations and facts."""
    summary: str = Field(..., description="Objective summary of verified evidence")
    confirmed_facts: list[str] = Field(default_factory=list)
    reported_claims: list[str] = Field(default_factory=list)
    inferred_points: list[str] = Field(default_factory=list)
    sources: list[str] = Field(default_factory=list)
    confidence_score: float = Field(default=0.8, ge=0.0, le=1.0)


class UserExplanationResponse(BaseModel):
    """User-facing communication structured around what changed, why it matters, evidence, uncertainty."""
    headline: str = Field(..., description="Concise non-alarmist headline")
    what_changed: str = Field(..., description="What specifically changed in the event state")
    why_it_matters: str = Field(..., description="Personalized or regional impact rationale")
    evidence: str = Field(..., description="Supporting verified evidence summary")
    uncertainty: str = Field(..., description="Disclosed limits of knowledge and uncertainty")
    suggested_posture: Literal["monitor", "reroute", "delay_trip", "defer_to_official"] = "monitor"
    official_guidance_reference: str | None = Field(
        default=None, description="Official Seattle/WSDOT emergency agency instruction if applicable"
    )
